[.recap]
== Exibit B

[.statement.pull-right]
a scoring engine [detail]#-- 2009#

[NOTE.speaker]
====
*Describe the context and the domain*
====

[.terminal, background-color="black"]
== !
....

           +-----------------------------------------------+
           |                                               |
           |  +-----------------------------------+        |
           |  |                                   |        |
           |  |          Boundary: SOAP           |        |
           |  |                                   |        |
           |  +-----------------------------------+        |
           |  |                                   |        |
           |  |               EJB                 |        |
           |  |                                   |        |
           |  +-----------------------------------+        |
           |                                               |
           |                                               |
           |  +--------+   +-------+   +----------+        |
           |  |        |   |       |   |          |        |
           |  | JAX-WS |   |  JPA  |   |  DROOLS  |        |
           |  |        |   |       |   |          |        |
           |  +--------+   +-------+   +----------+        |
           |                                               |
           |                                               |
           |                                 JBoss 4.2.x   |
           |                                               |
           +-----------------------------------------------+

....

[.right]
== Business value?

[.pull-right]
Webservices are so hard to sell. +
[pull-right]#*Can you visualize this? A UI?*#


[.terminal, background-color="black"]
== !
....

           +-----------------------------------------------+
           |                                               |
           |  +--------------------+--------------+        |
           |  |                    |              |        |
           |  |   Boundary: SOAP   |     JSF      |        |
           |  |                    |              |        |
           |  +--------------------+--------------+        |
           |  |                                   |        |
           |  |               EJB                 |        |
           |  |                                   |        |
           |  +-----------------------------------+        |
           |                                               |
           |                                               |
           |  +--------+   +-------+   +----------+        |
           |  |        |   |       |   |          |        |
           |  | JAX-WS |   |  JPA  |   |  DROOLS  |        |
           |  |        |   |       |   |          |        |
           |  +--------+   +-------+   +----------+        |
           |                                               |
           |                                               |
           |                                 JBoss 4.2.x   |
           |                                               |
           +-----------------------------------------------+

....

[NOTE]
[role="speaker"]
====
* That was the initial approach- which I didn't like
* I personally dislike JSF
* After further discussion with business - the need was for mobile UI
** Primefaces didn't make much sense in such case (remember 2009)
* The app took ages to deploy so the development was hell
** 25 minuts with full caching
** I'm blaming the workstations - but still had to find another way
====

[.terminal, background-color="black"]
== !

....
    +-----------------------------------------------+
    |                                               |
    |  +-----------------+-----------------+        |         +---------------+
    |  |                 |                 |        |         |               |
    |  | Boundary: SOAP  |  REST endpoint  | <--------------+ |   Dedicated   |
    |  |                 |                 |        |         |    mobile     |
    |  +-----------------+-----------------+        |         |  Single Page  |
    |  |                                   |        |         |  Application  |
    |  |               EJB                 |        |         |               |
    |  |                                   |        |         |               |
    |  +-----------------------------------+        |         +---------------+
    |                                               |
    |                                               |
    |  +--------+   +-------+   +----------+        |
    |  |        |   |       |   |          |        |
    |  | JAX+WS |   |  JPA  |   |  DROOLS  |        |
    |  |        |   |       |   |          |        |
    |  +--------+   +-------+   +----------+        |
    |                                               |
    |                                               |
    |                                 JBoss 4.2.x   |
    |                                               |
    +-----------------------------------------------+

....

[NOTE]
[role="speaker"]
====
* That was simple - write and endpoint, deploy and never come back
* Develop the application externally, independently
* My UI was one service, everything else was another
* That wasn't really a microservice - but it made me think...
====

[.recap-red]
== Note to self

[.statement]
*Keep* separate things *separately*

[NOTE]
[role="speaker"]
====
* Things change with various pace. If they differ, treat them differently.
* A Maslov hammer
//TODO: sprawdzić definicję młotka maslova
====

== Microservices checklist

* icon:square-o[] Small business domain
* icon:square-o[] Independent; independently deployed
* icon:square-o[] Running in it's own process
* icon:square-o[] Managing it's data
* icon:square-o[] Loosely integrated using common communication protocols

[NOTE.speaker]
====
Let me introduce microservices checklist
====

== Microservices checklist

* icon:check-square-o[] Small business domain
* icon:minus-square-o[] Independent; independently deployed
* icon:minus-square-o[] Running in it's own process
* icon:minus-square-o[] Managing it's data
* icon:check-square-o[] Loosely integrated using common communication protocols

[NOTE.speaker]
====
Told you - it's a journey
====


== Retrospective

[NOTE.speaker]
====
While we are not there yet with microservices - there are things to improve in our day to day development process.

Lessons learned
====


== !

[quote, James Lewis]
____
We define *libraries* as components that are linked into a program and called using in-memory calls, while *services* are out-of-process components who communicate with remote procedure calls
____

[NOTE.speaker]
====
* If we use libraries, compiler is out friend (check is there are any PHP developers present)
* Checks are in design time, before test / uat / production deployment
* With a new architecture, who tells us something went wrong?

(wait for it)

* Client when they get an HTTP503
====


== Consumer Driven Contracts

(...) drives the development of the *Provider* from its *Consumers* point of view, which means consumer describes *what and how it wants to receive the information* (in a form of a contract) and then *provider implements the service following the given contract*.


[NOTE.speaker]
====
* Can we mitigate it - sure
* Producer validates the present API, against various consumers expectations
* Consumers check against providers' generated data samples (wiremocks / docker stubs)
====
