[.recap]
== Exibit C

[.statement.pull-right]
huge image repository [detail]#-- 2007#

[NOTE]
[role="speaker"]
====
* I worked in education business with traditional publishers
* our big data are images and movies
* 8TB of data in files & 100GB of data in database
====

[.terminal, background-color="black"]
== !

....
+--------------------------------------+
|                                      |
|         web / controllers            |
|                                      |
+-----------+--------------------------+
            |
            | (1)       ^
            |           |
            v           | (5)
                        |
+-------------------------------------+
|                                     |
|         application logic           |
|                                     |
+--+-------------------------+--------+
   |                         |
   | (2)   ^                 | (4)
   |       |                 |
   v       | (3)             v
           |
+----------+--+    +------------------+
|             |    |                  |
|    MySQL    |    |    filesystem    |
|             |    |                  |
+-------------+    +------------------+
....

[NOTE]
[role="speaker"]
====
* A very simple flow. I'd say simplistic
* That's not much unless:
** The DB is denormalized MySQL
** Files are randomly spread throughout the drive
** Badly designed SQL queries
** Your app is a PHP application
* That was a Structs architecture written in PHP.
** That didnt stand a test of time
* Initially no caching. That database temp tables
* *And now they want you to make search faster*
** Where you'd rather throw this whole shite away
====

[.right]
== Business value?

[.pull-right]
The search function is unbelievably slow +
[pull-right]#*can't work with it*#


[.topic.recap.red-border]
== Note to self

[.statement]
There is *no* such thing as *legacy* 
-- what can't be killed, becomes  
[pull-right]#*business as usual*#

[.terminal, background-color="black"]
== !
....
        Proxy

       +-----+                                 +------------------+
       |     |         /*                      |                  |
+----------------+-------------------------->  |                  |
       |     |   |                             |  The Old stuff   |
       |     |   |                             |                  +--------+
       |     |   |                             |                  |        |
       |     |   |                             +------------------+        |
       |     |   |                                                         |
       |     |   |                                                         |  Elastic Search
       |     |   |                                                         |  data push
       |     |   |                                                         |
       |     |   |                                                         |
       |     |   |                             +------------------+        |
       |     |   |     /search                 |                  |        |
       |     |   +-------------------------->  |                  | <------+
       |     |                                 |  Elastic Search  |
       |     |                                 |       index      |
       |     |                                 |                  |
       +-----+                                 +------------------+
....

[NOTE]
[role="speaker"]
====
* That was the idea.
* The design looked solid
* The project never happened - due to various things

* You can delegate functionality in that way in various projects
** Semantic search for a legacy portal
** Advanced browsing for asset store
** One-off shot functionalities
* You build it, you cash it, you close it
====

[.recap-red]
== Note to self

[.statement]
Once observed -- *everything is* +
*a* not always micro
[pull-right]#*service*# +


[NOTE]
[role="speaker"]
====
* That brings me to another example
* Depending on your definition, what is microservice
** How micro should be the service
** Or size doesnt matter - but responsibility
* If you bound the context, aggregate - is it enough for microservice
====

== Microservices checklist

* icon:check-square-o[] Small business domain
* icon:check-square-o[] Independent; independently deployed
* icon:check-square-o[] Running in it's own process
* icon:check-square-o[] Managing it's data
* icon:check-square-o[] Loosely integrated using common communication protocols

== Retrospective

[quote, Distributed Systems (2007) - Principles & Paradigms, Andrew Tanenbaum]
____
(...) as every parent of a small child knows, converting a large object into small fragments is considerably easier than the reverse process.
____

// == !
//
// * Te same koncepcją mają różne znaczenie w rożnych obszarach +
// [detail]#modele kanoniczne, DDD itp#
// * Nie ma możliwości przeprowadzenia spójnej aktualizacji w systemie rozproszonym, po kilku bazach danych
// * Jak zarządzać potencjalnym brakiem spójności danych

[NOTE.speaker]
====
* Distributed Systems (2007) - Principles & Paradigms. Chapter 7, consistency and replication
** It's fairly academic. If you looking for something easier there is *Designing Data-Intensive Applications* by Martin Kleppmann
* Yeah, what about data?? What have I done?
* I've introduced replication? What I though it through? What are the consequences? How I introduced it? Is it performant?
* What is there is an error? Are there any business rules for mistakes, cache misses etc?
** Like in airlines? With overbooking
====

[.terminal, background-color="black"]
== !

....
Write through

  update query       +--------------------------+         +----------------------------------+
-------------------->| update denormalized view |-------->| update persistent (master) store |
                     +--------------------------+         +----------------------------------+


Write behind

  update query   +----------------------------------+            +---------------------------+
---------------->| update persistent (master) store |----------->| update denormalized views |
                 +----------------------------------+            +---------------------------+


Read through

  read query          +--------------------------+               +---------------------------+
<---------------------| update denormalized view |<--------------|   read persistent store   |
                      +--------------------------+               +---------------------------+

....

[NOTE.speaker]
====
In here were are caching, which is a special case for replication. 
Depending on the architecture we work with 

* consistency (is the set of data same between nodes)
** what data is in our read / query model
* coherence (has each copy of the data abide the same rules)
** how the data got into the read / query model
====